version: "3.8"
networks:
  app:
    driver: bridge

services:
  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   image: app-server
  #   container_name: app-server
  #   volumes:
  #     - ${BACKEND_SOURCE_PATH}:/usr/src/app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo
  #   env_file: .env
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - app

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   image: app-client
  #   container_name: app-client
  #   volumes:
  #     - ${FRONTEND_SOURCE_PATH}:/usr/app
  #   depends_on:
  #     - server
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    links: 
        - mongo:mongo
    restart: unless-stopped
    networks:
      - app